"""Docker orchestration helpers for failure injection.

Two mechanisms cover all 12 failures:
  * container stop/start          -> the "<datastore> down" failures
  * a generated compose override  -> the env-toggle / config / resource failures

The override file (docker-compose.faults.yml) is written next to the base
compose, layered on top with `-f`, and the target service is force-recreated so
it picks up the injected environment. Recovery deletes the override and
recreates the service from the base compose again.

Set FI_DRY_RUN=1 to print every command instead of executing it — useful to
preview exactly what will happen before touching real containers.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

# failure_injection/ lives inside the ecommerce/ folder next to docker-compose.yml.
COMPOSE_DIR = Path(os.getenv("COMPOSE_DIR", Path(__file__).resolve().parent.parent))
BASE_COMPOSE = "docker-compose.yml"
FAULTS_COMPOSE = "docker-compose.faults.yml"

DRY_RUN = os.getenv("FI_DRY_RUN", "").lower() in ("1", "true", "yes")


def _compose_cmd() -> list[str]:
    """Prefer `docker compose` (v2); fall back to legacy `docker-compose`."""
    if shutil.which("docker"):
        return ["docker", "compose"]
    if shutil.which("docker-compose"):
        return ["docker-compose"]
    return ["docker", "compose"]  # let it error clearly if neither exists


def run(cmd: list[str]) -> int:
    printable = " ".join(cmd)
    if DRY_RUN:
        print(f"[dry-run] {printable}")
        return 0
    print(f"+ {printable}")
    return subprocess.call(cmd, cwd=str(COMPOSE_DIR))


def _faults_path() -> Path:
    return COMPOSE_DIR / FAULTS_COMPOSE


# --- container stop/start --------------------------------------------------
def stop(service: str) -> None:
    run(_compose_cmd() + ["-f", BASE_COMPOSE, "stop", service])


def start(service: str) -> None:
    run(_compose_cmd() + ["-f", BASE_COMPOSE, "start", service])


# --- compose override (env / config / resources) --------------------------
def _serialize_service_block(service: str, config: dict) -> str:
    """Render a minimal, predictable compose override for one service.

    Supports scalar keys (e.g. restart, mem_limit) and a nested `environment`
    mapping — which is all the failures here need.
    """
    lines = [
        "# AUTO-GENERATED by failure_injection. Safe to delete.",
        "services:",
        f"  {service}:",
    ]
    for key, value in config.items():
        if key == "environment" and isinstance(value, dict):
            lines.append("    environment:")
            for k, v in value.items():
                lines.append(f'      {k}: "{v}"')
        else:
            lines.append(f'    {key}: "{value}"')
    return "\n".join(lines) + "\n"


def apply_override(service: str, config: dict) -> None:
    """Write the override for `service` and force-recreate just that service."""
    content = _serialize_service_block(service, config)
    if DRY_RUN:
        print(f"[dry-run] write {FAULTS_COMPOSE}:\n{content}")
    else:
        _faults_path().write_text(content)
    run(
        _compose_cmd()
        + ["-f", BASE_COMPOSE, "-f", FAULTS_COMPOSE,
           "up", "-d", "--no-deps", "--force-recreate", service]
    )


def remove_override(service: str) -> None:
    """Delete the override and recreate `service` from the base compose."""
    path = _faults_path()
    if DRY_RUN:
        print(f"[dry-run] rm {FAULTS_COMPOSE}")
    elif path.exists():
        path.unlink()
    run(
        _compose_cmd()
        + ["-f", BASE_COMPOSE, "up", "-d", "--no-deps", "--force-recreate", service]
    )